spring:
  application:
    name: ribbon-consumer

server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka,http://localhost:8002/eureka,http://localhost:8003/eureka
