spring:
  application:
    name: xyptservice
# 默认端口号，也可以用java jar命令启动服务并指定端口号，java -java XXX.jar --server.port = 8961
server:
  port: 8960
eureka:
  client:
    service-url:
      ####  配置一个eureka注册中心地址，即单节点配置 ####
      defaultZone: http://localhost:8000/eureka
      ####  配置多个eureka注册中心地址，实现高可用  ####
      #defaultZone: http://localhost:8001/eureka,http://localhost:8002/eureka,http://localhost:8003/eureka
#swagger:
#  base-package: com.demo.xyptservice.web